from __future__ import annotations

from .database import uj

def _fmt_mb(n) -> str:
    return f"{n:.2f} MB" if isinstance(n, (int, float)) else "-"

def model_report(model: dict, runs: list[dict]) -> str:
    a = uj(model.get("analysis"), {}) or {}
    goals = uj(model.get("goals"), {}) or {}
    plans = uj(model.get("plans"), {}) or {}
    bench = a.get("benchmark", {})
    b = a.get("bottlenecks", {})

    lines = [
        f"# ModelSmith Report: {model['name']}",
        "",
        f"- **Model ID:** `{model['id']}`",
        f"- **Framework:** {model['framework']}",
        f"- **Uploaded:** {model['created_at']}",
        f"- **SHA-256:** `{model['sha256']}`",
        "",
        "## 1. Model analysis",
        "",
        "| Metric | Value |",
        "|---|---|",
        f"| Parameters | {a.get('total_params', 0):,} |" if a else "",
        f"| Parameter size | {_fmt_mb(a.get('param_size_mb'))} |",
        f"| File size | {_fmt_mb(a.get('file_size_mb'))} |",
        f"| Compute | {a.get('total_flops', 0) / 1e6:.2f} MFLOPs/forward |",
        f"| Input shape | {' × '.join(str(d) for d in a.get('input_shape', []))} |",
        f"| Architecture class | {a.get('arch', '-')} |",
        "",
        "### Layer breakdown (top contributors)",
        "",
        "| Layer | Type | Params | Share |",
        "|---|---|---|---|",
    ]
    total = max(a.get("total_params", 1), 1)
    for l in (a.get("layers") or [])[:8]:
        if l.get("params"):
            lines.append(f"| {l['name']} | {l['type']} | {l['params']:,} | "
                         f"{100 * l['params'] / total:.1f}% |")

    lines += [
        "",
        "## 2. Benchmark profile",
        "",
        f"- Measured latency (CPU): **{bench.get('latency_ms', '-')} ms** mean, "
        f"{bench.get('p95_ms', '-')} ms p95 over {bench.get('runs', 0)} runs",
        f"- Throughput: {bench.get('throughput_fps', '-')} inferences/s",
        "",
        "### Bottleneck notes",
        "",
    ]
    lines += [f"- {n}" for n in (b.get("notes") or [])]

    lines += [
        "",
        "## 3. Deployment goals",
        "",
        f"- Objective: `{goals.get('objective', 'balanced')}`",
        f"- Target hardware: `{goals.get('target_hardware', 'cpu-server')}`",
        f"- Minimum accuracy retention: {goals.get('min_accuracy_pct', '-')}%",
        "",
        "## 4. Ranked optimization plans",
        "",
        "| # | Plan | Techniques | Size ↓ | Latency ↓ | Acc. retention |",
        "|---|---|---|---|---|---|",
    ]
    for p in (plans.get("valid") or []):
        pred = p["predicted"]
        lines.append(
            f"| {p['rank']} | {p['plan_id']} ({p['tagline']}) | "
            f"{', '.join(p['technique_labels'])} | {pred['size_saved_pct']}% | "
            f"{pred['latency_gain_pct']}% | {pred['accuracy_retention_pct']}% |")
    if plans.get("rejected"):
        lines += ["", "_Filtered out by compatibility/accuracy rules:_"]
        for p in plans["rejected"]:
            lines.append(f"- `{p['plan_id']}`: {'; '.join(p['rejected_because'])}")

    if runs:
        lines += ["", "## 5. Execution history & benchmarks"]
        for r in runs:
            bm = uj(r.get("benchmark"), {}) or {}
            base, opt = bm.get("baseline", {}), bm.get("optimized", {})
            ag = (bm.get("output_agreement") or {}).get("agreement_pct")
            lines += [
                "",
                f"### Run `{r['id']}`: {r['plan_name']} ({r['status']})",
                "",
                f"- Executed: {r['created_at']}",
                f"- Baseline: {_fmt_mb(base.get('size_mb'))}, "
                f"{base.get('latency_ms', '-')} ms",
                f"- Optimized: {_fmt_mb(opt.get('size_mb'))}, "
                f"{opt.get('latency_ms', '-')} ms",
                f"- **Size saved: {bm.get('size_saved_pct', '-')}%** | "
                f"**Latency gain: {bm.get('latency_gain_pct', '-')}%** | "
                f"Output agreement: {ag if ag is not None else 'n/a'}",
                f"- Artifacts: {', '.join(x['name'] for x in (uj(r.get('artifacts')) or []))}"
                if uj(r.get("artifacts")) else "- Artifacts: none",
            ]
            repro = uj(r.get("repro"), {}) or {}
            if repro:
                v = repro.get("versions", {})
                lines += [
                    "",
                    "<details><summary>Reproducibility metadata</summary>",
                    "",
                    "```json",
                    str(repro).replace("'", '"'),
                    "```",
                    "</details>",
                ]
    else:
        lines += ["", "_No optimization runs executed for this model yet._"]

    lines += [
        "",
        "---",
        "_Generated by ModelSmith · Intelligent AI Model Optimization & "
        "Deployment Platform._",
    ]
    return "\n".join(x for x in lines if x is not None)

def project_report(project: dict, models: list[dict], runs_by_model: dict) -> str:
    lines = [
        f"# ModelSmith Project Report: {project['name']}",
        "",
        project.get("description") or "",
        "",
        f"- **Models:** {len(models)}",
        f"- **Generated:** {project.get('updated_at', '')}",
        "",
        "| Model | Framework | Size | Best run | Size saved | Agreement |",
        "|---|---|---|---|---|---|",
    ]
    total_saved = 0.0
    best_overall = None
    for m in models:
        runs = runs_by_model.get(m["id"]) or []
        success = [r for r in runs if r.get("status") == "success"]
        if success:
            best = max(success, key=lambda r: (uj(r.get("benchmark"), {}) or {})
                       .get("size_saved_pct", 0))
            bm = uj(best.get("benchmark"), {}) or {}
            saved = bm.get("size_saved_pct")
            total_saved += saved or 0
            ag = (bm.get("output_agreement") or {}).get("agreement_pct")
            if best_overall is None or (saved or 0) > best_overall[1]:
                best_overall = (m["name"], saved or 0, best.get("plan_name"))
            lines.append(f"| {m['name']} | {m['framework']} | "
                         f"{(m.get('size_bytes') or 0) / 1e6:.1f} MB | "
                         f"{best.get('plan_name', '-')} | "
                         f"{saved if saved is not None else '-'}% | "
                         f"{ag if ag is not None else '-'}% |")
        else:
            lines.append(f"| {m['name']} | {m['framework']} | "
                         f"{(m.get('size_bytes') or 0) / 1e6:.1f} MB | "
                         "_no runs yet_ | - | - |")
    if best_overall:
        lines += ["",
                  f"**Best measured result:** {best_overall[1]}% size saved on "
                  f"'{best_overall[0]}' via {best_overall[2]}.",
                  "",
                  f"**Cumulative size saved across successful runs:** {round(total_saved, 1)}% "
                  "(sum of per-run wins; models optimized once each)."]
    lines += [
        "",
        "## Run details",
        "",
    ]
    for m in models:
        runs = runs_by_model.get(m["id"]) or []
        if not runs:
            continue
        lines += [f"### {m['name']}", ""]
        for r in runs:
            bm = uj(r.get("benchmark"), {}) or {}
            ag = (bm.get("output_agreement") or {}).get("agreement_pct")
            lines.append(
                f"- `{r['id']}` **{r.get('plan_name')}** ({r.get('status')}, "
                f"{r.get('execution_mode') or 'platform'}): "
                f"size −{bm.get('size_saved_pct', '-')}%, "
                f"latency −{bm.get('latency_gain_pct', '-')}%, "
                f"agreement {ag if ag is not None else 'n/a'}")
        lines.append("")
    lines += [
        "---",
        "_Generated by ModelSmith · Intelligent AI Model Optimization & "
        "Deployment Platform._",
    ]
    return "\n".join(x for x in lines if x is not None)
